blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: com/ibm-saas-platform/CICD-Playbook
    about: Much help can be found in the docs
  - name: Chat on Slack
    url: https://ibm.enterprise.slack.com/archives/C02LN72F1R6
    about: "#ibm-mcsp-gitops"
